<?php
error_reporting(0);

header("Content-Type: application/json"); 
header("Cache-Control: no-cache");


$headers = apache_request_headers();

$skey = $_SERVER['HTTP_SKEY'];
$pkey = $_SERVER['HTTP_PKEY'];

//
include('dbconnect.php');
//capture entry
//Receiving entries in JSON
$params = json_encode((object) json_decode(file_get_contents('php://input'), TRUE));
//print_r($params);

//If no headers are sent
if($pkey == ""){

  $data = [ 'statuscode' => '403', 'status' => 'empty_key', 'message' => 'Public key (pkey) cannot be empty. Set it in header' ];
    header("HTTP/1.1 400");
    echo $json = json_encode( $data );
    die();
}


//Verify the right pkey were sent
include('dbconnect.php');
  $stmt = $mysqli -> prepare("SELECT id from scan2pay_merchant WHERE pkey = ?") or die(mysqli_error($mysqli));
  $stmt -> bind_param("s", $pkey) or die(mysqli_error($mysqli));
  $stmt->execute() or die(mysqli_error($mysqli));
  $stmt->bind_result($t);
  $stmt->fetch();

  if($t == ""){
  $data = [ 'statuscode' => '405', 'status' => 'invalid_key', 'message' => 'Invalid pKey' ];
  header("HTTP/1.1 404");
    echo $json = json_encode( $data );
    die();
  }



//include db
include("dbconnect.php");

// Get params
$myArray = json_decode($params, true);
$user = $myArray['auth'];
$pass = md5($myArray['pin']);
$recei_acctid = $myArray['qr'];
$productId = $myArray['productId'];
$tel = $myArray['payee_tel'];
$amount = $myArray['amount'];

///////

   /* Create a prepared statement */
      $stmt = $mysqli -> prepare("SELECT auth FROM alertco_users WHERE tel=? AND password=?");
      /* Bind parameters
         s - string, b - blob, i - int, etc */
      $stmt -> bind_param("ss", $user, $pass);
      /* Execute it */
      $stmt -> execute() or die(mysqli_error($mysqli));
      /* Bind results */
      $stmt -> bind_result($auth1);
      /* Fetch the value */
      $stmt -> fetch();

 

      if($auth1 != "member"){


      $data = [ 'statuscode' => '400', 'status' => 'no_user', 'message' => 'Wrong Combination' ];
      header("HTTP/1.1 400");
      echo $json = json_encode( $data );
      die();


      }
         
      //and start a session
     session_start();
     $_SESSION['username'] = "$user";
     
     include('dbconnect.php');
     //Update last login
     $lastlogin = date("D d, M, Y g:i a");
     mysqli_query($mysqli, "update alertco_users set lastlogin = '$lastlogin' where tel = '$user'");
     


        //if everything is OK, then charge the individual 
        /////////////////////////*******************************//////////////////////////////////
      


include("dbconnect.php");

//Check the payee
$re = mysqli_query($mysqli, "select * from alertco_users where acctid = '".$recei_acctid."'") or die(mysqli_error(mysqli));
$rw = mysqli_fetch_array($re);
//
$recei_tel = $rw['tel'];
//
 

//Get database
 include('dbconnect.php');


  //Get the token from the scab2pay profile
   $rw = mysqli_query($mysqli, "select * from scan2pay_card where tel = '$tel'") or die(mysqli_error($mysqli));
   $row = mysqli_fetch_array($rw);
   $token = $row['cardtoken'];
   //get this person's details
   $rww = mysqli_query($mysqli, "select * from alertco_users where tel = '$tel'") or die(mysqli_error($mysqli));
   $rown = mysqli_fetch_array($rww);
   $fname = $rown['fname'];
   $lname = $rown['lname'];
   $email = $rown['email'];


  //Take money from tel /////////////////
  $ip = getenv('HTTP_CLIENT_IP')?:
  getenv('HTTP_X_FORWARDED_FOR')?:
  getenv('HTTP_X_FORWARDED')?:
  getenv('HTTP_FORWARDED_FOR')?:
  getenv('HTTP_FORWARDED')?:
  getenv('REMOTE_ADDR');


  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

//Disable CURLOPT_SSL_VERIFYHOST and CURLOPT_SSL_VERIFYPEER by
//setting them to false.
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

  curl_setopt($ch, CURLOPT_URL, 'https://api.gladepay.com/payment');
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n    \"action\":\"charge\",\n    \"paymentType\":\"token\",\n    \"token\":\"".$token."\",\n    \"user\": {\n        \"firstname\":\"".$fname."\",\n        \"lastname\":\"".$lname."\",\n        \"email\":\"".$email."\",\n        \"ip\":\"".$ip."\",\n        \"fingerprint\": \"hgshgsjdhjdhj\"\n    },\n    \"amount\":\"".$amount."\"\n}\n");
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');


  $headers = array();
  $headers[] = 'Content-Type: application/json';
  $headers[] = 'Key: Me2tkKOHckVb7zBVGmI29kJLhT3pkUIF8Yx';
  $headers[] = 'Mid: GP_cxEXfFwj13go1dU7KfQrIyCXMrkKEGgm';  
  $headers[] = 'Cache-Control: no-cache';
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

  $result = curl_exec($ch);

  if (curl_errno($ch)) {

      $data = [ 'statuscode' => '402', 'status' => 'no_connection', 'message' => 'Error establishing a connection' ];
      header("HTTP/1.1 400");
      echo $json = json_encode( $data );
      die();
      //echo 'Error:' . curl_error($ch);
  
  }else{

    //Check status
    $res = json_decode($result, true);
        $status = $res['status'];
        $transref = $res['txnRef'];
        $message = $res['message'];

        //Split QRcode (if a product)
        $text = $_GET['qrcode'];
        $strings = explode('*',$text);
        $productid = $strings[1]; //exploded from*
        $productid = $myArray['productId'];

        if($status == "200"){
          //Save record
          mysqli_query($mysqli, "insert into scan2pay_in (status, naration, productid, tel, acctid, amount, payee_tel, payee_name, payee_email, transref, date, day, month, year) values ('Completed', 'Payment', '$productid', '".$recei_tel."', '".$recei_acctid."', '".$amount."', '".$tel."', '".$fname." ".$lname."', '".$email."', '".$transref."', '".date("d-m-Y")."', '".date("d")."', '".date("m")."', '".date("Y")."')") or die(mysqli_error($mysqli));
          
          //Cashback
          if($amount >= 100){
          mysqli_query($mysqli, "insert into scan2pay_in (status, naration, productid, tel, acctid, amount, payee_tel, payee_name, payee_email, transref, date, day, month, year) values ('Completed', 'Cashback', '$productid', '".$tel."', '".$acctid."', '5', 'SCAN2PAY', 'SCAN2PAY', 'SCAN2PAY', '".$transref."', '".date("d-m-Y")."', '".date("d")."', '".date("m")."', '".date("Y")."')") or die(mysqli_error($mysqli));

          //Get upline and pay
                $rwup = mysqli_query($mysqli, "select * from alertco_users where tel = '$tel'") or die(mysqli_error($mysqli));
                $rowup = mysqli_fetch_array($rwup);
                $upline = $rowup['up1'];
                if($upline != ""){ //Pay
                     mysqli_query($mysqli, "insert into scan2pay_in (status, naration, productid, tel, amount, payee_tel, payee_name, payee_email, transref, date, day, month, year) values ('Completed', 'Commission on ".$fname." ".$lname." Txn', '$productid', '".$upline."', '10', 'SCAN2PAY', 'SCAN2PAY', 'SCAN2PAY', '".$transref."', '".date("d-m-Y")."', '".date("d")."', '".date("m")."', '".date("Y")."')") or die(mysqli_error($mysqli));
                }

              }//If greater than 100


          //Get recipient names
          //get this person's details
       $rww = mysqli_query($mysqli, "select * from alertco_users where tel = '$recei_tel'") or die(mysqli_error($mysqli));
       $rown = mysqli_fetch_array($rww);  

             //Send Email////////////////////////////////
              $toemail = $rown['email']; 
              $amount = $amount;
              $name = "".$rown['fname']." ".$rown['lname']."";
              $the_tel = $recei_tel;
              //*****************************
  //Send SMS now
    $headers = 'From: info@service.alertco.net <info@service.alertco.net>' . "\r\n";
    $headers .= "Reply-To: info@service.alertco.net <info@service.alertco.net>\r\n";
    $headers .= "MIME-Version: 1.0\r\n"; 
    $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

    $to = $toemail;
    $subject = "SCAN2PAY: PAYMENT NOTIFICATION";
 

 $message = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width"/>

    <!-- For development, pass document through inliner -->
    <style type="text/css">
        * { margin: 0; padding: 0; font-size: 100%; font-family: "Avenir Next", "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; line-height: 1.65; }

img { max-width: 100%; margin: 0 auto; display: block; }

body, .body-wrap { width: 100% !important; height: 100%; background: #f8f8f8; }

a { color: #71bc37; text-decoration: none; }

a:hover { text-decoration: underline; }

.text-center { text-align: center; }

.text-right { text-align: right; }

.text-left { text-align: left; }

.button { display: inline-block; color: white; background: #71bc37; border: solid #71bc37; border-width: 10px 20px 8px; font-weight: bold; border-radius: 4px; }

.button:hover { text-decoration: none; }

h1, h2, h3, h4, h5, h6 { margin-bottom: 20px; line-height: 1.25; }

h1 { font-size: 32px; }

h2 { font-size: 28px; }

h3 { font-size: 24px; }

h4 { font-size: 20px; }

h5 { font-size: 16px; }

p, ul, ol { font-size: 16px; font-weight: normal; margin-bottom: 20px; }

.container { display: block !important; clear: both !important; margin: 0 auto !important; max-width: 580px !important; }

.container table { width: 100% !important; border-collapse: collapse; }

.container .masthead { padding: 80px 0; background: #71bc37; color: white; }

.container .masthead h1 { margin: 0 auto !important; max-width: 90%; text-transform: uppercase; }

.container .content { background: white; padding: 30px 35px; }

.container .content.footer { background: none; }

.container .content.footer p { margin-bottom: 0; color: #888; text-align: center; font-size: 14px; }

.container .content.footer a { color: #888; text-decoration: none; font-weight: bold; }

.container .content.footer a:hover { text-decoration: underline; }
    </style>

    <style type="text/css">

    /* Your custom styles go here */

    </style>
</head>
<body>
<table class="body-wrap">
    <tr>
        <td class="container">

            <!-- Message start -->
            <table>
                <tr>
                    <td align="center" class="masthead">

                        <h1>SCAN2PAY</h1>

                    </td>
                </tr>
                <tr>
                    <td class="content">

                        <h2>Payment Notification</h2>
                        <h3>NGN '.number_format($amount, 2).' Credit</h3>
                        <p>Hi, '.$name.'<br>
                        You have recieved payment of NGN '.number_format($amount, 2).' from '.$fname.' '.$lname.'. 
                        <br><br>
                        Invoice ID: <strong>'.$transref.'</strong>
                        <br>
                        Amount:NGN <strong>'.number_format($amount, 2).'</strong>
                        <br>
                        Date: <strong>'.date("d-m-Y").'</strong>
                        </p>

                          

                    </td>
                </tr>
            </table>

        </td>
    </tr>
    <tr>
        <td class="container">

            <!-- Message start -->
            <table>
                <tr>
                    <td class="content footer" align="center">
                        <p>Sent by <a href="#">SCAN2PAY</a>, <br>Plot 55A, F. I. Ikem Link, Off Ofem Oboma Road, CHOOS Estate, Apo, Federal Capital Territory, Abuja, Nigeria</p>
                        <p><a href="mailto:">info@scan2paynow.com</a> | Call: +234817 643 0329, +234809 119 9322</p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>
</body>
</html>';

//echo $message;

//die();

//Send the message
mail($to, $subject, $message, $headers);

//SEND SMS/////////////////////
          $the_tel = (float)$the_tel;
          $the_tel = "234$the_tel";
          $the_tel = urlencode($the_tel);
          //send SMS
          
          //using cURL 
          $message = urlencode("You have received payment of NGN ".number_format($amount, 2)." from '".$fname." ".$lname."', on SCAN2PAY service. View details on https://dashboard.scan2paynow.com");
          
          //
            $curl_handle=curl_init();
            curl_setopt($curl_handle,CURLOPT_URL,"http://fancysms.com/api/sms/sendsms?username=alertco&password=adahson734?A&sender=SCAN2PAY&recipient=$the_tel&message=$message");
            curl_setopt($curl_handle,CURLOPT_CONNECTTIMEOUT,2);
            curl_setopt($curl_handle,CURLOPT_RETURNTRANSFER,1);
            $buffer = curl_exec($curl_handle);
            curl_close($curl_handle);

/////////////////////////////

              //*****************************
           ///////////////////////////////////////////

          //Register out record
          mysqli_query($mysqli, "insert into scan2pay_out (productid, tel, amount, recipient, recipient_name, transref, date, day, month, year) values ('$productid', '".$tel."', '".$amount."', '$recei_tel', '".$rown['fname']." ".$rown['lname']."', '".$transref."', '".date("d-m-Y")."', '".date("d")."', '".date("m")."', '".date("Y")."')") or die(mysqli_error($mysqli));

/////*******************************Commission email for Upline1******************************///////
 if($amount >= 100){
          //Get ulpline commission names
          //get this person's details
       $rww = mysqli_query($mysqli, "select * from alertco_users where tel = '$upline'") or die(mysqli_error($mysqli));
       $rown = mysqli_fetch_array($rww);  

             //Send Email////////////////////////////////
              $toemail = $rown['email']; 
              $amount = $amount;
              $name = "".$rown['fname']." ".$rown['lname']."";
              $the_tel = $recei_tel;
              //*****************************

      //Send SMS now
    $headers = 'From: info@service.alertco.net <info@service.alertco.net>' . "\r\n";
    $headers .= "Reply-To: info@service.alertco.net <info@service.alertco.net>\r\n";
    $headers .= "MIME-Version: 1.0\r\n"; 
    $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

    $to = $toemail;
    $subject = "SCAN2PAY: COMMISSION PAYMENT NOTIFICATION";
 

 $message = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width"/>

    <!-- For development, pass document through inliner -->
    <style type="text/css">
        * { margin: 0; padding: 0; font-size: 100%; font-family: "Avenir Next", "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; line-height: 1.65; }

img { max-width: 100%; margin: 0 auto; display: block; }

body, .body-wrap { width: 100% !important; height: 100%; background: #f8f8f8; }

a { color: #71bc37; text-decoration: none; }

a:hover { text-decoration: underline; }

.text-center { text-align: center; }

.text-right { text-align: right; }

.text-left { text-align: left; }

.button { display: inline-block; color: white; background: #71bc37; border: solid #71bc37; border-width: 10px 20px 8px; font-weight: bold; border-radius: 4px; }

.button:hover { text-decoration: none; }

h1, h2, h3, h4, h5, h6 { margin-bottom: 20px; line-height: 1.25; }

h1 { font-size: 32px; }

h2 { font-size: 28px; }

h3 { font-size: 24px; }

h4 { font-size: 20px; }

h5 { font-size: 16px; }

p, ul, ol { font-size: 16px; font-weight: normal; margin-bottom: 20px; }

.container { display: block !important; clear: both !important; margin: 0 auto !important; max-width: 580px !important; }

.container table { width: 100% !important; border-collapse: collapse; }

.container .masthead { padding: 80px 0; background: #71bc37; color: white; }

.container .masthead h1 { margin: 0 auto !important; max-width: 90%; text-transform: uppercase; }

.container .content { background: white; padding: 30px 35px; }

.container .content.footer { background: none; }

.container .content.footer p { margin-bottom: 0; color: #888; text-align: center; font-size: 14px; }

.container .content.footer a { color: #888; text-decoration: none; font-weight: bold; }

.container .content.footer a:hover { text-decoration: underline; }
    </style>

    <style type="text/css">

    /* Your custom styles go here */

    </style>
</head>
<body>
<table class="body-wrap">
    <tr>
        <td class="container">

            <!-- Message start -->
            <table>
                <tr>
                    <td align="center" class="masthead">

                        <h1>SCAN2PAY</h1>

                    </td>
                </tr>
                <tr>
                    <td class="content">

                        <h2>Commission Payment Notification</h2>
                        <h3>NGN 10.00 Credit</h3>
                        <p>Hi, '.$name.'<br>
                        You have recieved payment of NGN 10.00 from SCAN2PAY as commission for transaction of '.$fname.' '.$lname.'. 
                        <br><br>
                        Invoice ID: <strong>'.$transref.'</strong>
                        <br>
                        Amount:NGN <strong>'.number_format($amount, 2).'</strong>
                        <br>
                        Date: <strong>'.date("d-m-Y").'</strong>
                        </p>

                          

                    </td>
                </tr>
            </table>

        </td>
    </tr>
    <tr>
        <td class="container">

            <!-- Message start -->
            <table>
                <tr>
                    <td class="content footer" align="center">
                        <p>Sent by <a href="#">SCAN2PAY</a>, <br>Plot 55A, F. I. Ikem Link, Off Ofem Oboma Road, CHOOS Estate, Apo, Federal Capital Territory, Abuja, Nigeria</p>
                        <p><a href="mailto:">info@scan2paynow.com</a> | Call: +234817 643 0329, +234809 119 9322</p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>
</body>
</html>';

//echo $message;

//die();

//Send the message
mail($to, $subject, $message, $headers);

}


/////////////////////////////////////

           
      $data = [ 'statuscode' => '00', 'status' => 'success', 'ref' => $transref, 'productid' => $productid, 'amount' => $amount, 'message' => 'Payment successful' ];
      header("HTTP/1.1 200");
      echo $json = json_encode( $data );
      die();



        }else{


          //XXXXXXXXXXXXXXXXXXXXXs///////////DEMO/////////////////

     //        //Check the payee
            $re = mysqli_query($mysqli, "select * from alertco_users where acctid = '".$recei_acctid."'") or die(mysqli_error(mysqli));
            $rw = mysqli_fetch_array($re);
            //
            $recei_tel = $rw['tel'];
            //
             

            //Get database
             include('dbconnect.php');


              //Get the token from the scab2pay profile
               $rw = mysqli_query($mysqli, "select * from scan2pay_card where tel = '$tel'") or die(mysqli_error($mysqli));
               $row = mysqli_fetch_array($rw);
               $token = $row['cardtoken'];
               //get this person's details
               $rww = mysqli_query($mysqli, "select * from alertco_users where tel = '$tel'") or die(mysqli_error($mysqli));
               $rown = mysqli_fetch_array($rww);
               $fname = $rown['fname'];
               $lname = $rown['lname'];
               $email = $rown['email'];

     //Save record

             $digits = 9;
             $transref = rand(pow(10, $digits-1), pow(10, $digits)-1);
             $productid = $myArray['productId'];

          mysqli_query($mysqli, "insert into scan2pay_in (status, naration, productid, tel, acctid, amount, payee_tel, payee_name, payee_email, transref, date, day, month, year) values ('Completed', 'Payment', '$productid', '".$recei_tel."', '".$recei_acctid."', '".$amount."', '".$tel."', '".$fname." ".$lname."', '".$email."', '".$transref."', '".date("d-m-Y")."', '".date("d")."', '".date("m")."', '".date("Y")."')") or die(mysqli_error($mysqli));

          $data = [ 'statuscode' => '00', 'status' => 'success', 'productid' => $productid, 'amount' => $amount, 'ref' => $transref, 'message' => 'Payment successful' ];
          header("HTTP/1.1 200");
          echo $json = json_encode( $data );
          die();

          //XXXXXXXXXXXXXXXXXXXX//////////END DEMO///////////



      //$data = [ 'statuscode' => '407', 'status' => 'error', 'message' => $message ];
      //header("HTTP/1.1 400");
      //echo $json = json_encode( $data );
      //die();

      //echo "Error: $message";

        }

  }
  curl_close($ch);


     
      die();

      /////////////////////////*******************************//////////////////////////////////

       
   /* Close connection */
   $mysqli -> close();
?>